appschoolscheduler/urls.py
from django.conf.urls import url
from appschoolscheduler import views

app_name = "appschoolscheduler"

urlpatterns = [
    url(r'^schedule/$', views.schedule, name = "schedule"),
    url(r'^schedule/(?P<order>[0-9]+)/(?P<day>[0-9]+)$', views.setSchedule, name = "setschedule"),
    url(r'^schedule/(?P<order>[0-9]+)/(?P<day>[0-9]+)/(?P<scheduled_subject>\w+)$', views.planLesson, name = "planlesson"),
    url(r'^schedule/presence/(?P<order>[0-9]+)/(?P<day>[0-9]+)/(?P<subject>\w+)$', views.presenceOfStudent, name = "presenceofstudent"),
]

ednevnik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^registration/$', views.registration, name="registration"),
    url(r'^admin/', admin.site.urls),
    url(r'^schools/', include('appschools.urls')),
    url(r'^profiles/', include('appprofiles.urls')),
    url(r'^overviews/', include('appoverviews.urls')),
    url(r'^messages/', include('appmessages.urls')),
    url(r'^subjects/', include('appschoolsubjects.urls')),
    url(r'^schoolscheduler/', include('appschoolscheduler.urls')),
    url(r'^permissiondenied$', views.denied, name="denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appschoolscheduler/models.py
from django.db import models
import datetime
from appschoolsubjects.models import SchoolSubject
from appschools.models import SchoolClass
from appprofiles.models import Profile


# Create your models here.

class SchoolScheduler(models.Model):
    school_class = models.ForeignKey(SchoolClass)
    subject = models.ForeignKey(SchoolSubject)
    teacher = models.ForeignKey(Profile, null = True)
    day = models.IntegerField()
    order = models.IntegerField()
    shift = models.IntegerField()
    active = models.BooleanField(default = True)

    def __str__(self):
        return "{}".format(self.subject)

class LessonPlan(models.Model):
    scheduled_subject = models.ForeignKey(SchoolScheduler)
    lesson = models.TextField(null = True)
    date = models.DateField(default=datetime.date.today)
    subject = models.ForeignKey(SchoolSubject, null = True)
    def __str__(self):
        return "{}".format(self.scheduled_subject)

class PresenceOfStudent(models.Model):
    date = models.DateField(default=datetime.date.today)
    scheduled_subject = models.ForeignKey(SchoolScheduler)
    justified = models.BooleanField(default = True)
    notes = models.TextField(blank = True)
    student = models.ForeignKey(Profile)
    semester = models.IntegerField()
    def __str__(self):
        return "{}".format(self.student)

appschoolscheduler/forms.py
from django.forms import ModelForm
from django import forms

from appschoolsubjects.models import SchoolSubject
from .models import LessonPlan,PresenceOfStudent

class ScheduleSubjectForm(ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ScheduleSubjectForm,self).__init__(*args, **kwargs)
        self.fields['school_subject'].queryset = SchoolSubject.objects.filter(school_class = user.school_class_id)

    school_subject = forms.ModelChoiceField(label = False, queryset = SchoolSubject.objects.all())

    class Meta:
        model = SchoolSubject
        fields = ('school_subject',)

class LessonPlanForm(ModelForm):

    class Meta:
        model = LessonPlan
        fields = ('lesson',)

class PresenceOfStudentForm(ModelForm):

    class Meta:
        model = (PresenceOfStudent)
        fields = ('notes', 'justified')

appschoolscheduler/views.py
from django.shortcuts import render, redirect

from appprofiles.models import Profile
from .models import SchoolScheduler,LessonPlan,PresenceOfStudent
from appschoolsubjects.models import SchoolSubject

from appschoolscheduler.forms import ScheduleSubjectForm
# Create your views here.

def schedule(request):
    current_user = Profile.objects.get(user = request.user)
    if current_user.school_class == None:
        return render(request, "permission_denied.html", {"msg": "You dont have permissions to view the scheduler. Only class teachers can view the schedules to their classes.","current_user": current_user,})
    schedule = SchoolScheduler.objects.filter(school_class = current_user.school_class)

    form = ScheduleSubjectForm(user = current_user)

    return render(request, "appschoolscheduler/schedule.html",
        {
            "current_user": current_user,
            "form": form,
            "schedule": schedule,
        })

def setSchedule(request, order, day):
    current_user = Profile.objects.get(user = request.user)
    print("order: %s" % order)
    print("day: %s" % day)
    print("razred: %s" % current_user.school_class)
    print("smjena: %s" % current_user.school_class.shift)
    print("predmet: %s" % request.POST.get("school_subject", ""))

    if SchoolScheduler.objects.filter(day = day, order = order, school_class = current_user.school_class, active = True):
        current_active = SchoolScheduler.objects.get(day = day, order = order, school_class = current_user.school_class, active = True)
        current_active.active = False
        current_active.save()

    query = SchoolScheduler(
        school_class = current_user.school_class,
        subject = SchoolSubject.objects.get(id = request.POST.get("school_subject", "")),
        day = day,
        order = order,
        shift = current_user.school_class.shift,
        teacher = SchoolSubject.objects.get(id = request.POST.get("school_subject", "")).teacher
    )
    query.save()

    return redirect("/schoolscheduler/schedule")

def planLesson(request, order, day, scheduled_subject):
    current_user = Profile.objects.get(user = request.user)
    s_subject = SchoolScheduler.objects.get(id = scheduled_subject)
    print("####################################################")
    print(type(s_subject.subject))
    query = LessonPlan(
        scheduled_subject = SchoolScheduler.objects.get(id = scheduled_subject),
        lesson = request.POST.get("lesson", ""),
        subject = s_subject.subject,
    )
    query.save()
    return redirect("/profiles/home")

def presenceOfStudent(request, order, day, subject):
    current_user = Profile.objects.get(user = request.user)
    print(SchoolScheduler.objects.get(id = subject))
    print(request.POST.get("justified", ""))
    print(request.POST.get("notes", ""))
    print(Profile.objects.get(id = request.POST.get("students", "")))

    query = PresenceOfStudent(
        scheduled_subject = SchoolScheduler.objects.get(id = subject),
        justified = bool(request.POST.get("justified", "")),
        notes = request.POST.get("notes", ""),
        student = Profile.objects.get(id = request.POST.get("students", "")),
        semester = current_user.school.semester,
    )
    query.save()

    return redirect("/profiles/home")

templates/appschoolscheduler/schedule.html
{% extends "base.html" %}

{% block body_block%}
{% load staticfiles %}
{% load get_time %}

<div class="container">
  <div class="table-container">
    <h3 class="table-information text-center">Schedule</h3>
      <table class="table-responsive-sm">
          <tr>
            <th></th>
            <th>Ponedjeljak</th>
            <th>Utorak</th>
            <th>Srijeda</th>
            <th>Cetvrtak</th>
            <th>Petak</th>
          </tr>
          {% for i in "1234567"%}
          <tr>
            <td>{% get_class_time current_user i %}</td>
            {% for j in "12345" %}
            <td>
              <!--<p>{% get_subject current_user i j %}<a data-toggle="modal" data-target="#{{ i }}_{{ j }}" class="btn btn-primary">{{ i }}_{{ j }}</a></p>-->
            {% get_subject current_user i j %}<a data-toggle="modal" data-target="#{{ i }}_{{ j }}"><sup><i class="far fa-edit mx-2"></i></sup></a>

            </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
  </div>
</div>


{% for i in "1234567" %}
  {% for j in "12345" %}
  <div class="modal fade" id="{{ i }}_{{ j }}" tabindex="-1" role="dialog" aria-labelledby="{{ i }}_{{ j }}Label" aria-hidden="true">
  	<div class="modal-dialog modal-dialog-centered" role="document">
  		<div class="modal-content text-center">
  			<div class="modal-header">
  				<h5 class="modal-title text-center" id="{{ i }}_{{ j }}Label">{{i}}.sat, dan {{j}}</h5>
  				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
  					<span aria-hidden="true">&times;</span>
  				</button>
  			</div>
        <form class="" action="{% url "appschoolscheduler:setschedule" order=i day=j %}" method="post">
          <div class="mt-2">{% csrf_token %}
            {{ form }}
            <div class="d-block">
              <input type="submit" name="" value="submit" class="submit">
            </div>
          </div>
        </form>

  		</div>
  	</div>
  </div>
  {% endfor %}
{% endfor %}
{% endblock %}