appoverviews/urls.py
from django.conf.urls import url
from appoverviews import views

app_name = "appoverviews"

urlpatterns = [
    url(r'^subject/(?P<subject_id>[0-9]+)$', views.subjectToTeach, name="subjectToTeach"),
    url(r'^student/(?P<student_id>[0-9]+)$', views.student, name="student"),
    url(r'^teacher/(?P<teacher_id>[0-9]+)$', views.teacher, name="teacher"),
    url(r'^principal/(?P<principal_id>[0-9]+)$', views.principal, name="principal"),
]

appschoolsubjects/urls.py
from django.conf.urls import url
from appschoolsubjects import views

app_name = "appschoolsubjects"

urlpatterns = [
    url(r'^add/schoolsubject$', views.addSchoolSubject, name="addSchoolSubject"),
    url(r'^add/(?P<subject_id>[0-9]+)/(?P<student_id>[0-9]+)$', views.addGradeToStudent, name="addGradeToStudent"),
]

ednevnik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^registration/$', views.registration, name="registration"),
    url(r'^admin/', admin.site.urls),
    url(r'^schools/', include('appschools.urls')),
    url(r'^profiles/', include('appprofiles.urls')),
    url(r'^overviews/', include('appoverviews.urls')),
    url(r'^messages/', include('appmessages.urls')),
    url(r'^subjects/', include('appschoolsubjects.urls')),
    url(r'^schoolscheduler/', include('appschoolscheduler.urls')),
    url(r'^permissiondenied$', views.denied, name="denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appoverviews/models.py
from django.db import models

# Create your models here.

appoverviews/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from appprofiles.models import Profile
from appschools.models import SchoolClass
from appschoolsubjects.models import SchoolSubject, Grades
from appschoolscheduler.models import PresenceOfStudent

from appschoolsubjects.forms import AddGradeToStudent

@login_required(login_url='/profiles/login/')
def subjectToTeach(request, subject_id):
    """ Subject To teach
    This form shows a subject of a teacher and all the students in the class.
    In this form the teacher can add grades and final grades to a student.

    forms: addGradeToStudentForm

    models: Profile, SchoolSubject, Grades

    return: permission_denied.html, appoverviews/class.html
    """
    current_user = Profile.objects.get(user = request.user)
    if current_user.is_teacher == False:
        return render(request, "permission_denied.html", {"msg": "You dont have permissions to access this form. Only class teachers can access this form.","current_user": current_user,})

    subject = SchoolSubject.objects.get(id = subject_id)
    school_class = SchoolClass.objects.get(id = subject.school_class.id)

    grades_first = Grades.objects.filter(school_subject = subject, semester = 1, is_final = False)
    grades_second = Grades.objects.filter(school_subject = subject, semester = 2, is_final = False)

    grades_first_final = Grades.objects.filter(school_subject = subject, semester = 1, is_final = True)
    grades_second_final = Grades.objects.filter(school_subject = subject, semester = 2, is_final = True)

    grades_dict_first = {}
    grades_dict_second = {}
    grades_dict_first_final = {}
    grades_dict_second_final = {}

    for grade in grades_first_final:
        grades_dict_first_final[grade.student] = ""
        if grade.grade:
            grades_dict_first_final[grade.student] = grade.grade

    for grade in grades_second_final:
        grades_dict_second_final[grade.student] = ""
        if grade.grade:
            grades_dict_second_final[grade.student] = grade.grade

    for grade in grades_first:
        if grade.student not in grades_dict_first:
            grades_dict_first[grade.student] = []
        grades_dict_first[grade.student].append(grade.grade)

    for grade in grades_second:
        if grade.student not in grades_dict_second:
            grades_dict_second[grade.student] = []
        grades_dict_second[grade.student].append(grade.grade)

    students_of_class = Profile.objects.filter(is_student = True, school_class = school_class)
    addGradeToStudentForm = AddGradeToStudent()
    return render(request, "appoverviews/class.html", {
        "current_user": current_user,
        "subject": subject,
        "students": students_of_class,
        "school_class": school_class,
        "grades_dict_first": grades_dict_first,
        "grades_dict_second": grades_dict_second,
        "grades_dict_first_final": grades_dict_first_final,
        "grades_dict_second_final": grades_dict_second_final,
        "addGradeToStudentForm":addGradeToStudentForm,
    })

@login_required(login_url='/profiles/login/')
def student(request, student_id):
    current_user = Profile.objects.get(user = request.user)

    student = Profile.objects.get(id = student_id)

    absences_justified = PresenceOfStudent.objects.filter(student = student, justified = True)
    absences_unjustified = PresenceOfStudent.objects.filter(student = student, justified = False)
    
    subjects = SchoolSubject.objects.filter(school_class = student.school_class)
    grades_first = Grades.objects.filter(student = student, semester = 1, is_final = False)
    grades_second = Grades.objects.filter(student = student, semester = 2, is_final = False)

    grades_first_final = Grades.objects.filter(student = student, semester = 1, is_final = True)
    grades_second_final = Grades.objects.filter(student = student, semester = 2, is_final = True)

    grades_dict_first = {}
    grades_dict_second = {}
    grades_dict_first_final = {}
    grades_dict_second_final = {}

    for grade in grades_first_final:
        grades_dict_first_final[grade.school_subject] = ""
        if grade.grade:
            grades_dict_first_final[grade.school_subject] = grade.grade

    for grade in grades_second_final:
        grades_dict_second_final[grade.school_subject] = ""
        if grade.grade:
            grades_dict_second_final[grade.school_subject] = grade.grade
            print(grades_dict_second_final[grade.school_subject])

    for grade in grades_first:
        if grade.school_subject not in grades_dict_first:
            grades_dict_first[grade.school_subject] = []
        grades_dict_first[grade.school_subject].append(grade.grade)

    for grade in grades_second:
        if grade.school_subject not in grades_dict_second:
            grades_dict_second[grade.school_subject] = []
        grades_dict_second[grade.school_subject].append(grade.grade)

    return render(request, "appoverviews/student.html", {
        "current_user":current_user,
        "student": student,
        "subjects": subjects,
        "grades_dict_first": grades_dict_first,
        "grades_dict_second": grades_dict_second,
        "grades_dict_first_final":grades_dict_first_final,
        "grades_dict_second_final":grades_dict_second_final,
        "absences_justified":absences_justified,
        "absences_unjustified":absences_unjustified,
    })

@login_required(login_url='/profiles/login/')
def teacher(request, teacher_id):
    """
    show the information of the teacher
    """
    teacher = Profile.objects.get(id = teacher_id)
    subjects = SchoolSubject.objects.filter(teacher=teacher)
    return render(request, "appoverviews/teacher.html", {
        "teacher": teacher,
        "subjects":subjects,
    })

@login_required(login_url='/profiles/login/')
def principal(request, principal_id):
    """
    shows the information of the principal
    """
    principal = Profile.objects.get(id = principal_id)
    pass

templates/appoverviews/class.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
{% load app_filters %}
<div class="container table-container mt-5">
	<h1 class="text-center table-information">
		<span class="d-block h2">{{ subject }}</span> <span class="h4 fw">{{ school_class }}</span>
	</h1>
	<h3 id="semesterNumber" class="d-none">{{ school_class.school.semester }}</h3>
	
	
	<div class="nav-tabs-wrapper">
		<ul class="nav nav-tabs mt-5 text-center justify-content-center">
			<li class="nav-item">
				<a class="nav-link " id="firstSemesterTab" data-toggle="tab" href="#firstSemester">First semester</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" id="secondSemesterTab" data-toggle="tab" href="#secondSemester">Second semester</a>
			</li>
		</ul>
	</div>
	<div class="row">
		<div class="col-md-12 text-center mt-3">
			<input type="search" class="search-for-table" id="search" placeholder="Search" autofocus>

		</div>
	</div>
	<div class="tab-content">
		<div class="tab-pane " id="firstSemester">
			<div class="container">
				<div class="row ">
					<table class="text-center table-responsive-md">
						<tr >
							<th>First name</th>
							<th>Lastname</th>
							<th>Grades</th>
							<th>Final</th>
							<th>Add grade</th>
						</tr>
						{% for student in students %}
						<tr>
							<td>{{ student.user.first_name }}</td>
							<td>{{ student.user.last_name }}</td>
							<td>
								{% for key, values in grades_dict_first.items %}
								{% if student == key %}
								{% for grade in values %}
								{{ grade }}
								{% endfor %}
								{% endif %}
								{% endfor %}
							</td>
							<td>
								{% if  grades_dict_first_final|get_item:student %}
								{{ grades_dict_first_final|get_item:student }}
								{% endif %}
							</td>
							<td>
								{% if school_class.school.semester == 1 %}
								{% if not grades_dict_first_final|get_item:student %}
								<a data-toggle="modal" data-target="#exampleModal{{ student.id }}">Add</a>
								{% endif %}
								{% endif %}
							</td>

						</tr>
						{% endfor %}
					</table>

				</div>
			</div>

		</div>
		<div class="tab-pane" id="secondSemester">
			<div class="container">
				<div class="row">
					<table class="text-center table-responsive-md">
						<tr>
							<th>First name</th>
							<th>Lastname</th>
							<th>Grades</th>
							<th>final</th>
							<th>Add grade</th>
						</tr>
						{% for student in students %}
						<tr>
							<td>{{ student.user.first_name }}</td>
							<td>{{ student.user.last_name }}</td>
							<td>
								{% for key, values in grades_dict_second.items %}
								{% if student == key %}
								{% for grade in values %}
								{{ grade }}
								{% endfor %}
								{% endif %}
								{% endfor %}
							</td>
							<td>
								{% if  grades_dict_second_final|get_item:student %}
								{{ grades_dict_second_final|get_item:student }}
								{% endif %}
							</td>
							<td>
								{% if school_class.school.semester == 2 %}
								{% if not grades_dict_second_final|get_item:student %}
								<a data-toggle="modal" data-target="#exampleModal{{ student.id }}">Add</a>
								{% endif %}
								{% endif %}
							</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>

		</div>
	</div>
</div>

{% for student in students %}
<div class="modal fade" id="exampleModal{{ student.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Unesi ocjenu {{ student }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form class="" action="{% url "appschoolsubjects:addGradeToStudent" subject_id=subject.id student_id=student.id %}" method="post">
				<div class="modal-body">{% csrf_token %}
					{{ addGradeToStudentForm.as_p }}
					<input type="submit" name="" value="Submit" class="submit">
				</div>
			</form>

		</div>
	</div>
</div>
{% endfor %}

<script src="{% static 'js/js.js' %}"></script>
{% endblock %}

templates/appoverviews/classes.html
{% extends "base.html" %}
{% block body_block %}
<table class="vertical">
	<tr>
		<th>Broj</th>
		<th>Smjer</th>
		<th>Razrednik?</th>
	</tr>
	{% for class in classes %}
	<tr>
		<td>{{ class.class_number }}</td>
		<td>{{ class.class_direction }}</td>
		<td>{{ class.has_teacher }}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}

templates/appoverviews/my_class.html
{% extends "base.html"%}
{% load staticfiles %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'css/teacher_schoolclasses.css' %}">

  <h1 class="heading text-center mb-5">This is my class</h1>
  <table>
    <tr>
      <th>fname</th>
      <th>lname</th>
    </tr>
    {% for student in my_students %}
    <tr>
      <td>{{ student.user.first_name }}</td>
      <td>{{ student.user.last_name }}</td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/appoverviews/my_subjects.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body_block %}
<link rel="stylesheet" href="{% static 'css/teacher_schoolclasses.css' %}">
  <h1 class="heading text-center mb-5">Predmeti koje predajem</h1>
  <table>
    {% for subject in my_subjects %}
      <tr>
        <td>{{ subject.title }}</td>
        <td>{{ subject.school_class }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/appoverviews/principal.html
{% extends "base.html" %}

{% block body_block %}
  <h1>Principal info</h1>
{% endblock %}

templates/appoverviews/student.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<h3 id="semesterNumber" class="d-none">{{ current_user.school.semester }}</h3>


<div class="container main-section">
	<div class="container">
		<div class="row">
			<div class="col-md-2 text-center">
				<img src="/media/{{ student.profile_pic }}" alt="profile photo" class="profile-img">
			</div>
			<div class="col-md-2 my-auto text-center">
				<p class="light-theme-color h3 d-inline-block">{{ student.user.first_name }}</p>
				<p class="light-theme-color h3 d-inline-block">{{ student.user.last_name }}</p>
			</div>
			<div class="col-md-4 text-center my-auto">
				<p class="light-theme-color h3">{{ student.school }}</p>
				<p class="light-theme-color h4 fw">{{ student.school_class }}</p>
			</div>
		</div>
	</div>
</div>



			<div class="container table-container ">
					<h1 class="text-center">Student info</h1>
					<div class="nav-tabs-wrapper">
						<ul class="nav nav-tabs text-center justify-content-center">
							<li class="nav-item">
								<a class="nav-link" id="firstSemesterTab" data-toggle="tab" href="#firstSemester" >First semester</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" id="secondSemesterTab" data-toggle="tab" href="#secondSemester">Second semester</a>
							</li>
						</ul>
					</div>



					<div class="tab-content">
						<div class="tab-pane" id="firstSemester">
							<div class=" table-accessory col-md-3 text-center">
									<h3 class="fw borders-bottom">Izostanci (Prvo polugodiste)</h3>
									<p>Opravdani: {{ absences_justified_first.count }} <a type="" class="" data-toggle="modal" data-target="#absenceJHistoryModal"><i class="fas fa-info-circle"></i></a></p>
									<p>Neopravdani: {{ absences_unjustified_first.count }} <a type="" class="" data-toggle="modal" data-target="#absenceUHistoryModal"><i class="fas fa-info-circle"></i></a></p>
							</div>
							<table class="">
								<tr>
									<th>Subjects</th>
									<th>Grades</th>
									<th>Final</th>
								</tr>
								{% for subject in subjects %}
								<tr>
									<td>{{ subject }}</td>
									<td>
										{% for key, values in grades_dict_first.items %}

										{% if subject == key %}
										{% for grade in values %}
										{{ grade }}
										{% endfor %}
										{% endif %}

										{% endfor %}
									</td>
									<td>
										{% load app_filters %}
										{% if grades_dict_first_final|get_item:subject %}
										{{ grades_dict_first_final|get_item:subject }}
										{% endif %}
									</td>

								</tr>
								{% endfor %}
							</table>
						</div>

						<div class="tab-pane " id="secondSemester">
							<div class=" table-accessory col-md-3 text-center">
									<h3 class="fw borders-bottom">Izostanci (drugo polugodiste)</h3>
									<p>Opravdani: {{ absences_justified_first.count }} <a type="" class="" data-toggle="modal" data-target="#absenceJHistoryModal"><i class="fas fa-info-circle"></i></a></p>
									<p>Neopravdani: {{ absences_unjustified_first.count }} <a type="" class="" data-toggle="modal" data-target="#absenceUHistoryModal"><i class="fas fa-info-circle"></i></a></p>
							</div>
							<table class="">
								<tr>
									<th>Subjects</th>
									<th>Grades</th>
									<th>Final</th>
								</tr>
								{% for subject in subjects %}
								<tr>
									<td>{{ subject }}</td>
									<td>
										{% for key, values in grades_dict_second.items %}
											{% if subject == key %}
												{% for grade in values %}
													{{ grade }}
												{% endfor %}
											{% endif %}
										{% endfor %}
									</td>
									<td>
										{% load app_filters %}
										{% if grades_dict_second_final|get_item:subject %}
											{{ grades_dict_second_final|get_item:subject }}
										{% endif %}
									</td>
								</tr>
								{% endfor %}
							</table>
						</div>
					</div>
				</div>







<!-- MODAL -->
<div class="modal fade" id="absenceJHistoryModal" tabindex="-1" role="dialog" aria-labelledby="absenceJHistoryModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">
			<div class="modal-header">
				<h5 class="modal-title" id="absenceJHistoryModalLabel">Unesi podatke</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="content">
				{% for absence in absences_justified %}
					<p>{{ absence.scheduled_subject }} - {{absence.date}} - {{absence.notes}}</p>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="absenceUHistoryModal" tabindex="-1" role="dialog" aria-labelledby="absenceUHistoryModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">
			<div class="modal-header">
				<h5 class="modal-title" id="absenceUHistoryModalLabel">Unesi podatke</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="content">
				{% for absence in absences_unjustified %}
					<p>{{ absence.scheduled_subject }} - {{absence.date}} - {{absence.notes}}</p>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

<!-- ENDMODAL -->

<script src="{% static 'js/js.js' %}"></script>

{% endblock %}

templates/appoverviews/teacher.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}



<div class="container main-section">
	<div class="container">
		<div class="row">
	</div>
		<div class="row">
			<div class="col-md-2 text-center">
				<img src="/media/{{ teacher.profile_pic }}" alt="" class="profile-img">
			</div>
			<div class="col-md-2 my-auto text-center">
				<p class="light-theme-color h3 d-inline-block">{{ teacher.user.first_name }}</p>
				<p class="light-theme-color h3 d-inline-block">{{ teacher.user.last_name }}</p>
				<p class="light-theme-color h4 fw">{{ role }}</p>
			</div>
			<div class="col-md-4 text-center my-auto">
				<p class="light-theme-color h3">{{ teacher.school_class }}</p>
			</div>
		</div>
	</div>
</div>

<div class="container table-container">
	<h3 class="text-center table-information">Subjects the {{ teacher.user.first_name }} {{ teacher.user.last_name }}  teaches</h3>
		<table>
			<tr>
				<th>Subject</th>
				<th>Class</th>
			</tr>
			{% for subject in subjects %}
			<tr>
				<td>{{ subject.title }}</td>
				<td>{{ subject.school_class }}</td>
			</tr>
			{% endfor %}
		</table>
</div>


{% endblock %}

templates/appoverviews/teachers.html
{% extends "base.html" %}
{% block body_block %}
<table>
	<tr>
		<th>Ime</th>
		<th>Prezime</th>
		<th>razred</th>
	</tr>
	{% for teacher in teachers %}
	<tr>
		<td>{{ teacher.user.first_name }}</td>
		<td>{{ teacher.user.last_name }}</td>
		<td>{{ teacher.school_class }}</td>
	</tr>
	{% endfor %}
</table>
{% endblock %}