appoverviews/urls.py
from django.conf.urls import url
from appoverviews import views

app_name = "appoverviews"

urlpatterns = [
    url(r'^subject/(?P<subject_id>[0-9]+)$', views.subjectToTeach, name="subjectToTeach"),
    url(r'^student/(?P<student_id>[0-9]+)$', views.student, name="student"),
    url(r'^teacher/(?P<teacher_id>[0-9]+)$', views.teacher, name="teacher"),
    url(r'^principal/(?P<principal_id>[0-9]+)$', views.principal, name="principal"),
]

appprofiles/urls.py
from django.conf.urls import url
from appprofiles import views

app_name = "appprofiles"

urlpatterns = [
    url(r'^login/$', views.userLogin, name="login"),
    url(r'^logout/$', views.userLogout, name="logout"),
    url(r'^decline/$', views.userDecline, name="decline"),
    url(r'^home/$', views.homeView, name="home"),
    url(r'^teachers/$', views.teachers, name="teachers"),
    url(r'^students/$', views.students, name="students"),
]

appschoolscheduler/urls.py
from django.conf.urls import url
from appschoolscheduler import views

app_name = "appschoolscheduler"

urlpatterns = [
    url(r'^schedule/$', views.schedule, name = "schedule"),
    url(r'^schedule/(?P<order>[0-9]+)/(?P<day>[0-9]+)$', views.setSchedule, name = "setschedule"),
    url(r'^schedule/(?P<order>[0-9]+)/(?P<day>[0-9]+)/(?P<scheduled_subject>\w+)$', views.planLesson, name = "planlesson"),
    url(r'^schedule/presence/(?P<order>[0-9]+)/(?P<day>[0-9]+)/(?P<subject>\w+)$', views.presenceOfStudent, name = "presenceofstudent"),
]

ednevnik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^registration/$', views.registration, name="registration"),
    url(r'^admin/', admin.site.urls),
    url(r'^schools/', include('appschools.urls')),
    url(r'^profiles/', include('appprofiles.urls')),
    url(r'^overviews/', include('appoverviews.urls')),
    url(r'^messages/', include('appmessages.urls')),
    url(r'^subjects/', include('appschoolsubjects.urls')),
    url(r'^schoolscheduler/', include('appschoolscheduler.urls')),
    url(r'^permissiondenied$', views.denied, name="denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appprofiles/models.py
from django.db import models
from appschools.models import School, SchoolClass
from django.contrib.auth.models import User

# Create your models here.

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'profile_images/{0}/{1}'.format(instance.user.id, filename)

class Profile(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    school = models.ForeignKey(School, null=True, blank=True,on_delete=models.CASCADE)
    school_class = models.ForeignKey(SchoolClass, null = True, blank=True,on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to = user_directory_path, default = "profile_images/unknown.png")
    is_siteadmin = models.BooleanField(default = False)
    is_principal = models.BooleanField(default = False)
    is_teacher = models.BooleanField(default = False)
    is_student = models.BooleanField(default = False)
    language = models.CharField(max_length = 2, default="EN")
    theme = models.CharField(max_length = 30, default="dark")

    def __str__(self):
        return "{}".format(self.user)

class ActivationKeys(models.Model):
    user = models.ForeignKey(Profile)
    sec_key = models.CharField(max_length = 25)
    activated = models.BooleanField(default=False)

appprofiles/forms.py
from django import forms
from django.contrib.auth.models import User
from appprofiles.models import Profile
from appschools.models import SchoolClass

THEMES = (
    ("dark", "dark"),
    ("light", "light"),
)

class UserForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())
    #username = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Email'}), required=False)
    #password = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Password'}))
    first_name = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'email', )


class SAUserForm(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())
    #username = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Email'}), required=False)
    password = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Password'}))
    first_name = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(label = False, widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'email', 'password',)

class SiteAdminForm(forms.ModelForm):
    password = forms.CharField(label = False, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    confirm_password=forms.CharField(label = False, widget=forms.PasswordInput(attrs={'placeholder': 'Confirm password'}))
    class Meta():
        model = Profile
        fields = ()

    def clean(self):
        cleaned_data = super(SiteAdminForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class PrincipalForm(forms.ModelForm):
    is_teacher = forms.BooleanField(label="Je li predavac", required = False)
    class Meta():
        model = Profile
        fields = ('is_teacher','profile_pic',)

class AllTeachersOfSchool(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(AllTeachersOfSchool,self).__init__(*args, **kwargs)
        userProfile = Profile.objects.get(user = user)
        self.fields['teachers'].queryset = Profile.objects.filter(school = userProfile.school, is_teacher = True)

    teachers = forms.ModelChoiceField(queryset = Profile.objects.all(), label = False)

class TeacherForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = ('school_class','profile_pic',)

class StudentForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = ('profile_pic',)

class TeacherToClassForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TeacherToClassForm,self).__init__(*args, **kwargs)
        userProfile = Profile.objects.get(user = user)
        self.fields['teachers'].queryset = Profile.objects.filter(school = userProfile.school, is_teacher = True).filter(school_class = None)
        self.fields['classes'].queryset = SchoolClass.objects.filter(has_teacher = False).filter(school = userProfile.school, has_teacher = False)

    teachers = forms.ModelChoiceField(queryset = Profile.objects.all(), label = False)
    classes = forms.ModelChoiceField(queryset = SchoolClass.objects.all(), label = False)

class ChangeProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ChangeProfileForm, self).__init__(*args, **kwargs)
        userProfile = Profile.objects.get(user = user)
        self.fields['theme'].initial = userProfile.theme
        #theme = userProfile.theme
        #print(theme)

    theme = forms.ChoiceField(choices=THEMES)
    class Meta:
        model = Profile
        fields = ('theme',)

appprofiles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse

from appprofiles.models import Profile
from appschools.models import SchoolClass
from appschoolsubjects.models import SchoolSubject, Grades

from appprofiles.forms import UserForm, PrincipalForm, TeacherForm, StudentForm, TeacherToClassForm, ChangeProfileForm
from appschoolscheduler.forms import LessonPlanForm,PresenceOfStudentForm

from helper.accounts import getUsername

# Create your views here.

def userLogin(request):
    """ User login

    View for the user to login. Dont uses any forms. If not POST,
    the view return the login form. If POST, the view takes the
    username and password and try to login.
    The view has also the function to check if the user is active.
    If the user is not active, it means that the school is not active,
    and he cannot login. At first login he has to use the link sent to
    the users mail. The link has a SecKey at the end. This SecKey is used
    to check that this user made the registration. If the SecKey from the link
    and the SecKey for the user in the model are the same, the user and the
    school will be activated.

    returns: /schools/schoolactivation/, /profiles/home/, appprofiles/login.html

    """
    if request.user.is_authenticated(): return HttpResponse("Your are already logged in")
    error_msg = ""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            # User and School activation process
            if user.is_active:
                login(request,user)
                current_user = Profile.objects.get(user = request.user)
                print(request.session.get('sec_key'))
                if request.session.get('sec_key') and not current_user.school.is_active:
                    return redirect("/schools/schoolactivation/")
                return redirect('/profiles/home/')
        else:
            error_msg = "Wrong username or password. Please try again!"
            return render(request,"appprofiles/login.html", {"error_msg": error_msg})
    return render(request,"appprofiles/login.html", {})

@login_required(login_url='/profiles/login/')
def userLogout(request):
    """ User logout

    View for log out. Redirects to root "/"

    """
    logout(request)
    return redirect('/')

@login_required(login_url='/profiles/login/')
def userDecline(request):
    """ User decline

    Declines the user to work further because the school is not active.
    Log the user automatically out and throws a message.

    returns: 'Your school is not active!'
    """
    logout(request)
    return HttpResponse('Your school is not active!')

@login_required(login_url='/profiles/login/')
def homeView(request):
    current_user = Profile.objects.get(user = request.user)
    if not current_user.school.is_active: return redirect('/profiles/decline/')

    my_subjects = ""
    grades_first_dict = ""
    grades_second_dict = ""
    lesson_plan_form = ""
    presence_of_student = ""

    if current_user.is_principal:
        role = "principal"
        if current_user.is_teacher:
            role = "principal (teacher)"
    elif current_user.is_teacher:
        role = "teacher"

        my_subjects = SchoolSubject.objects.filter(teacher = current_user)
        lesson_plan_form = LessonPlanForm()
        presence_of_student = PresenceOfStudentForm()
        print(lesson_plan_form)
        print("WERE ARE HERE")
    elif current_user.is_student:
        role = "student"
        grades_first = Grades.objects.filter(student = current_user, semester = 1)
        grades_second = Grades.objects.filter(student = current_user, semester = 2)
        subjects = SchoolSubject.objects.filter(school_class = current_user.school_class)

        grades_first_dict = {}
        grades_second_dict = {}

        for subject in subjects:
            grades_first_dict[subject] = []
            grades_second_dict[subject] = []

        for grade in grades_first:
            grades_first_dict[grade.school_subject].append(grade.grade)

        for grade in grades_second:
            grades_second_dict[grade.school_subject].append(grade.grade)

    elif current_user.is_siteadmin: role = "site admin"

    if request.method == "POST":
            change_profile_form = ChangeProfileForm(data = request.POST, user = request.user)
            if change_profile_form.is_valid():
                print("Im in the change")

                change_profile = change_profile_form.save(commit = False)
                change_profile.theme = request.POST.get('theme', "")
                print(request.POST.get('theme', ""))
                current_user.theme = request.POST.get('theme', "")
                current_user.save()

                return HttpResponseRedirect(reverse('appprofiles:home', args=()))


    change_profile_form = ChangeProfileForm(user = request.user)
    print("###############################################")
    user_profile = {
        "current_user": current_user,
        "role": role,
        "my_subjects": my_subjects,
        'grades_first': grades_first_dict,
        'grades_second': grades_second_dict,
        "change_profile_form":change_profile_form,
        "lesson_plan_form": lesson_plan_form,
        "presence_of_student": presence_of_student,
    }
    return render(request,"appprofiles/home_view.html", user_profile)

@login_required(login_url='/profiles/login/')
def teachers(request):
    current_user = Profile.objects.get(user = request.user)
    teachers_of_my_school = Profile.objects.filter(school = current_user.school, is_teacher = True)
    if not current_user.is_siteadmin and not current_user.is_principal:
        return render(request, "permission_denied.html", {"msg": "You dont have permissions to access this form. Only class principals can access this form.","current_user": current_user,})

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        teacher_form = TeacherForm(request.POST, request.FILES)
        assing_teacher_to_class_form = TeacherToClassForm(data = request.POST, user = request.user)

        if user_form.is_valid() and teacher_form.is_valid():
            user = user_form.save(commit = False)
            user.username = getUsername(request.POST.get("first_name"),request.POST.get("last_name"))
            user.set_password("asd")
            user.save()

            teacher = teacher_form.save(commit = False)
            teacher.user = user
            teacher.school = current_user.school
            teacher.is_teacher = True
            teacher.profile_pic = teacher_form.cleaned_data['profile_pic']
            teacher.save()

            return HttpResponseRedirect(reverse('appprofiles:teachers', args=()))

        elif assing_teacher_to_class_form.is_valid():
            if assing_teacher_to_class_form.is_valid():
                teacher = request.POST.get("teachers")
                schoolClass = request.POST.get("classes")
                Profile.objects.filter(id = teacher).update(school_class=schoolClass)
                SchoolClass.objects.filter(id = schoolClass).update(has_teacher = True)
        else:
            return HttpResponse("Form not valid")

    teacher_form = TeacherForm()
    user_form = UserForm()
    assing_teacher_to_class_form = TeacherToClassForm(user = request.user)

    return render(request,"appprofiles/teachers.html", {
        "current_user": current_user,
        "teacher_form": teacher_form,
        "user_form": user_form,
        "teachers_of_my_school": teachers_of_my_school,
        "assing_teacher_to_class_form":assing_teacher_to_class_form,
    })

@login_required(login_url='/profiles/login/')
def students(request):
    current_user = Profile.objects.get(user = request.user)
    students_of_my_class = Profile.objects.filter(school_class = current_user.school_class, is_student = True)
    if not current_user.is_teacher: return render(request, "permission_denied.html", {"msg": "You are not a teacher. You cant create students."})
    if current_user.school_class == None: return render(request, "permission_denied.html", {"msg": "You dont have an class assigned. You cant create students."})

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        student_form = StudentForm(request.POST, request.FILES)
        if user_form.is_valid() and student_form.is_valid():
            user = user_form.save(commit = False)
            user.username = getUsername(request.POST.get("first_name"),request.POST.get("last_name"))
            user.set_password("asd")
            user.save()

            student = student_form.save(commit = False)
            student.user = user
            student.school = current_user.school
            student.school_class = current_user.school_class
            student.profile_pic = student_form.cleaned_data['profile_pic']
            student.is_student = True
            student.save()
            return HttpResponseRedirect(reverse('appprofiles:students', args=()))
        else:
            return HttpResponse("Form is not valid (appprofiles.students)")
    student_form = StudentForm()
    user_form = UserForm()
    return render(request, "appprofiles/students.html", {
        "current_user": current_user,
        "student_form": student_form,
        "user_form": user_form,
        "students_of_my_class":students_of_my_class
    })

templates/appprofiles/create_principal.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<!-- <link rel="stylesheet" href="{% static 'css/add_school_class.css' %}"> -->



  <form class="registration text-center" action="" method="post" enctype="multipart/form-data">
  <h1 class="heading">Create a principal</h1>

    {% csrf_token %}
    {{ user_form.as_p }}
    {{ principal_form.as_p}}

	<div class="btn">
    	<input class="submit" type="submit" name="" value="submit">
  	</div>
  </form>

{% endblock %}

templates/appprofiles/create_student.html
{% extends "base.html" %}

{% block body_block %}
  <h1>Create a student</h1>
  <form class="" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ student_form.as_p}}
    <input type="submit" name="" value="submit">
  </form>
{% endblock %}

templates/appprofiles/create_teacher.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

  <form class="" action="" method="post" enctype="multipart/form-data">

    <h1 class="heading">Create a teacher</h1>
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ teacher_form.as_p}}
    <input type="submit" name="" value="submit">

  </form>

  <fieldset>
    <legend>Teachers:</legend>
    <table>
      <tr>
        <th>fname</th>
        <th>lname</th>
      </tr>
      {% for teacher in teachers_of_my_school %}
        <tr>
          <td>{{ teacher.user.first_name }}</td>
          <td>{{ teacher.user.last_name }}</td>
        </tr>
      {% endfor %}
    </table>
  </fieldset>
{% endblock %}

templates/appprofiles/login.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<link rel="stylesheet" type='text/css' href="{% static 'css/skelet.css' %}" />
<link rel="stylesheet" type='text/css' href="{% static 'css/dark-theme-colors.css' %}" />


<div class="container center-block center-text">

	<div class="page mt-5">
		<form method="post" action="{% url 'appprofiles:login' %}">
			<div class="row justify-content-center">
				<div class="col-md-6">
					<h2 class="text-center">Log in</h2>
				</div>
			</div>

			{% csrf_token %}
			{# A more "HTML" way of creating the login form#}

			<div class="row justify-content-center">
				<div class="col-md-6">
					<label for="username" class="text-center registration">
						<input type="text" name="username" class="" placeholder="Username" required>
					</label>
				</div>
			</div>
	
			<div class="row justify-content-center">
				<div class="col-md-6"> 
					<label for="password" class="text-center registration">
						<input name="password" type="password" class="" placeholder="Password" required>
					</label>
				</div>
			</div>

			<div class="row justify-content-center">
				<div class="col-md-12 text-center">
					<input name="" value="Login" type="submit" class="submit outlinenone" placeholder="Log in">
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 text-center">	
					<a class="register-link" href="{% url "registration" %}">Register on Omikron</a>
				</div>
			</div>
		</form>
		<p class="error text-center">
			{% if error_msg %}
				{{ error_msg }}
			{% endif %}
		</p>
	</div>
</div>
{% endblock %}

templates/appprofiles/students.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 ">
            <h1 class="heading text-center mb-5 borders-bottom border-bottom-black">My students</h1>
        </div>
    </div>


    <div class="container table-container">
        <div class="col-md-12 text-right">
            <a type="" class="" data-toggle="modal" data-target="#createastudent"><i class="fas fa-plus-circle"></i> Create a student </a>
        </div>
        <div class="text-center">
                <input type="search" class="search-for-table" id="search" placeholder="Search" autofocus>
        </div>
        <table class="table-responsive-sm" id="table">
            <tr class="header">
                <th>Firstname</th>
                <th>Lastname</th>
                <th>View</th>
            </tr>
            {% for student in students_of_my_class %}
            <tr>
                <td>{{ student.user.first_name }}</td>
                <td>{{ student.user.last_name }}</td>
                <td><a href="{% url "appoverviews:student" student_id=student.id %}">View</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>


<!-- ############################ MODAL ############################################ -->
<div class="modal fade" id="createastudent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content text-center">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Unesi podatke</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form class="" action="" method="post" enctype="multipart/form-data">
				<div class="modal-body">{% csrf_token %}
          {{ user_form.as_p }}
          {{ student_form.as_p}}
					<input type="submit" name="" value="submit" class="submit">
				</div>
			</form>

		</div>
	</div>
</div>

{% endblock %}

templates/appprofiles/teacher_to_class.html
{% extends "base.html" %}

{% block body_block %}
<form class="" action="" method="post">{% csrf_token %}
  {{form.as_p }}
  <input type="submit" name="" value="Submit">
</form>

{% endblock %}

templates/appprofiles/teachers.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}


<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-12 ">
			<h1 class="heading text-center mb-5 borders-bottom border-bottom-black">Teachers</h1>
		</div>
	</div>

	



	<div class="container table-container">
		<div class="col-md-12 text-right">
				<a data-toggle="modal" data-target="#createTeacher"><i class="fas fa-plus-circle"></i> Create a teacher</a>
		</div>
		<div class="col-md-12 text-right">
				<a data-toggle="modal" data-target="#assignTeacher"><i class="fas fa-plus-circle"></i> Assign teacher to class</a>
		</div>

		<div class="text-center">
				<input type="search" class="search-for-table" id="search" placeholder="Search" autofocus>
				<table class="table-responsive-sm" id="table">
					<tr class="header">
						<th>Firstname</th>
						<th>Lastname</th>
						<th>View</th>
					</tr>
					{% for teacher in teachers_of_my_school %}
					<tr>
						<td>{{ teacher.user.first_name }}</td>
						<td>{{ teacher.user.last_name }}</td>
						<td><a href="{% url "appoverviews:teacher" teacher_id=teacher.id %}">View</a></td>
					</tr>
					{% endfor %}
				</table>
		</div>
	</div>
</div>





<!--#####################################  MODAL  ###########################################-->

<div class="modal fade" id="createTeacher" tabindex="-1" role="dialog"
aria-labelledby="createTeacherLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content text-center">
		<div class="modal-header ">
			<h5 class="modal-title" id="createTeacherLabel">Unesi podatke</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
		<form class="text-center form" id="form" action="" method="post" enctype="multipart/form-data">
			<div class="modal-body">{% csrf_token %}
				{{ user_form.as_p }}
				{{ teacher_form.as_p }}
				<input class="submit" type="submit" name="" value="Submit">
			</div>
		</form>

	</div>
</div>
</div>


<div class="modal fade" id="assignTeacher" tabindex="-1" role="dialog" aria-labelledby="assignTeacherLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="assignTeacherLabel">Unesi podatke</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form class="text-center" id="form" action="" method="post">
				<div class="modal-body">{% csrf_token %}
					{{ assing_teacher_to_class_form.as_p }}
					<input type="submit" name="" value="Submit" class="submit">
				</div>
			</form>

		</div>
	</div>
</div>


{% endblock %}