appmessages/urls.py
from django.conf.urls import url
from appmessages import views

app_name = "appmessages"

urlpatterns = [
    url(r'^contact/$', views.contactMsgHandler, name="contact_msg_handler"),
]

appprofiles/urls.py
from django.conf.urls import url
from appprofiles import views

app_name = "appprofiles"

urlpatterns = [
    url(r'^login/$', views.userLogin, name="login"),
    url(r'^logout/$', views.userLogout, name="logout"),
    url(r'^decline/$', views.userDecline, name="decline"),
    url(r'^home/$', views.homeView, name="home"),
    url(r'^teachers/$', views.teachers, name="teachers"),
    url(r'^students/$', views.students, name="students"),
]

appschools/urls.py
from django.conf.urls import url
from appschools import views

app_name = "appschools"

urlpatterns = [
    url(r'^schoolclasses/$', views.schoolClasses, name="schoolClasses"),
    url(r'^schoolsettings/', views.schoolSettings, name="schoolSettings"),
    url(r'^schoolactivation/(?P<sec_key>.*)/$', views.schoolActivation, name="schoolActivation"),
    url(r'^schoolactivation/', views.schoolActivation, name="schoolActivation"),
]

appschoolsubjects/urls.py
from django.conf.urls import url
from appschoolsubjects import views

app_name = "appschoolsubjects"

urlpatterns = [
    url(r'^add/schoolsubject$', views.addSchoolSubject, name="addSchoolSubject"),
    url(r'^add/(?P<subject_id>[0-9]+)/(?P<student_id>[0-9]+)$', views.addGradeToStudent, name="addGradeToStudent"),
]

ednevnik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^registration/$', views.registration, name="registration"),
    url(r'^admin/', admin.site.urls),
    url(r'^schools/', include('appschools.urls')),
    url(r'^profiles/', include('appprofiles.urls')),
    url(r'^overviews/', include('appoverviews.urls')),
    url(r'^messages/', include('appmessages.urls')),
    url(r'^subjects/', include('appschoolsubjects.urls')),
    url(r'^schoolscheduler/', include('appschoolscheduler.urls')),
    url(r'^permissiondenied$', views.denied, name="denied"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>E-Dnevnik</title>
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static '/images/favicon.ico' %}"/>
	<!-- Responsive meta tag -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Icons -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<!-- GOOGLE FONT -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700" rel="stylesheet">
	<!--Bootstrap 4-->
	<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
	<link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
	<!-- CSS -->
	<link rel="stylesheet" type='text/css' href="{% static 'css/skelet.css' %}" />
	<!--<link rel="stylesheet" type='text/css' href="{% static 'css/dark-theme-colors.css' %}" />-->
	{% if current_user %}
		{% with 'css/'|add:current_user.theme|add:'-theme-colors.css' as css_static %}
		  <link rel="stylesheet" type='text/css' href="{% static css_static %}" />
		{% endwith %}
	{% else %}
		<link rel="stylesheet" type='text/css' href="{% static 'css/dark-theme-colors.css' %}" />
	{% endif %}

	<!-- <link rel="stylesheet" type='text/css' href="{% static 'css/light-theme-colors.css' %}" /> -->
	{% if current_user.theme == "dark" %}

	{% endif %}
	<!--Bootstrap 4 script-->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
	<nav class="navbar navbar-dark navbar-expand-lg navbar-toggleable-sm  fixed-top" id="navbar">
		<div class="container">
			<a class="navbar-brand" href="{% url "index" %}">Omikron E-dnevnik</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			{% if user.is_authenticated %}
			<div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url "appprofiles:home" %}">My view</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">For principal</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="{% url "appprofiles:teachers" %}">Teachers</a>
							<a class="dropdown-item" href="{% url "appschools:schoolClasses" %}">Classes</a>
						</div>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">For teacher</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="{% url "appschoolsubjects:addSchoolSubject" %}">School subjects</a>
							<a class="dropdown-item" href="{% url "appschoolscheduler:schedule" %}">School schedule</a>
							<a class="dropdown-item" href="{% url "appprofiles:students" %}">Students</a>
						</div>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Help</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="{% url "appschools:schoolSettings" %}">School settings</a>
						</div>
					</li>
					{% if not user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url "appprofiles:login" %}">Login</a>
					</li>
					{% endif %}
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url "appprofiles:logout" %}">Logout</a>
					</li>
					{% endif %}
				</ul>
			</div>
			{% endif %}
		</div>
	</nav>


	<div class="container-fluid main-container">
		{% block body_block %}
		{% endblock %}
	</div>
			<footer class="footer text-center">
				<p>&copy; Copyrigt <span id="date"></span></p>
				<p>All right reserved. Powered by <b>Omnikron</b>.</p>
			</footer>
</body>
<script src="{% static 'js/date.js' %}"></script>
<script src="{% static 'js/scroll.js' %}"></script>
<script src="{% static 'js/search.js' %}"></script>
</html>

templates/confirmation.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>confirmation</title>
  </head>
  <body>
    <h1>you sent a message to omikron.ednevnik@gmail.com</h1>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
	<meta name="google" content="notranslate">
	<title>E-Dnevnik</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--Bootstrap 4-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<!-- GOOGLE FONT -->
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet">
	<!-- CSS -->
	<link rel="stylesheet" type='text/css' href="{% static 'css/index.css' %}" />
</head>
<body>
	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg  fixed-top " id="mainNav">
		<div class="container">
			<a class="navbar-brand" href="#page-top">Omikron eDnevnik</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url "appprofiles:home" %}">To App</a>
					</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link" href="{% url "appprofiles:login" %}">Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url "registration" %}">Register</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<header>
		<div class="container text-center">
			<h1>Dobrodosli Omikron  online dnevnik</h1>
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste assumenda unde ut debitis</p>
		</div>
	</header>

	<section>
		<div class="container">
			<iframe class="video" src="https://www.youtube.com/embed/K74_bKyNDd4?rel=0&amp;autoplay=0&showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
		</div>
	</section>

	<section id="services">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 mx-auto">
					<h2>Services we offer</h2>
					<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row text-center justify-content-center">

				<form class="" action="{% url "appmessages:contact_msg_handler" %}" method="post">{% csrf_token %}
					<h2 style="color: #e0e3e6">Contact us</h2>

					{{ msg_form.as_p }}
					<input type="submit" name="" value="Submit">
				</form>
			</div>
		</div>
	</section>

	<!-- Footer -->
	<footer class="py-5">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; Omikron 2018</p>
		</div>
		<!-- /.container -->
	</footer>
	<!--Bootstrap 4 script-->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/permission_denied.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/permission.css' %}">
<div class="container">
	<div class="msg mt-5">
		<h1>PERMISSION DENIED</h1>
		<h2>{{ msg }}</h2>	
	</div>
</div>

{% endblock %}

templates/registration.html
{% load staticfiles %}
{% block body_block %}
<!-- Responsive meta tag -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--Bootstrap 4-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!-- GOOGLE FONT -->
<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet">
<!-- CSS -->
<link rel="stylesheet" type='text/css' href="{% static 'css/skelet.css' %}" />
<link rel="stylesheet" type='text/css' href="{% static 'css/dark-theme-colors.css' %}" />

<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="{% url "index" %}">Omikron eDnevnik</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "appprofiles:home" %}">To App</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "appprofiles:login" %}">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <div class="container">
    <div>
      <div class="row justify-content-center">
        <h1>Register</h1>
      </div>
    </div>
  </div>


    <div class="container">
  <form class="text-center mt-5 register-form" action="{% url "registration" %}" method="post">

    {% csrf_token %}
      <div class="row">
        <div class="col-md-6 mt-3 registration "> 
          <h3>Site Admin data</h3>
          {{ userForm.as_table }}
          {{ siteAdminForm.as_table }}
        </div>
        <div class="col-md-6 mt-3 registration">
          <h3>School data</h3>
          {{ schoolForm.as_table }}
        </div>
      </div>
      <input class="submit" type="submit" name="" value="Register">
  </form>
    </div>
{% endblock %}